version: "3"

volumes:
  drupal-data:

services:
  drupal:
    build: .
    image: "sshaffer/customer-drupal"
    ports:
      - "8080:80"
    depends_on:
      - postgres
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "mypw"
    volumes:
      - drupal-data:/var/lib/postgresql/data
